controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

accueil:
    path: /
    controller: App\Controller\MenuController::acceuil
